compare/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib import admin


admin.autodiscover()
urlpatterns = [
    url(r'^djadmin/', include(admin.site.urls)),
    url(r'^', include('diapers.urls', namespace="diapers")),
]

urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT}),)


handler404 = 'diapers.views.error404'
handler500 = 'diapers.views.error500'

diapers/urls.py
__author__ = 'asorokoumov'
from django.conf.urls import url

from . import views
from views import *

urlpatterns = [

    url(r'^admin/$', views.admin, name='admin'),

    # admin
    url(r'^parse/parse_shop_catalog/$', views.parse_shop_catalog, name='parse_shop_catalog'),
    url(r'^parse/update_brand_list/$', views.update_brand_list, name='update_brand_list'),
    url(r'^parse/recreate/$', views.recreate, name='recreate'),
    url(r'^parse/prices/$', views.update_prices_and_availability, name='update_prices_and_availability'),
    url(r'^parse/manual/$', views.manual_parse, name='manual'),
    url(r'^parse/manual_parse_result/$', views.manual_parse_result, name='manual_parse_result'),


    #  New design
    url(r'^$', views.index, name='index'),
    url(r'^podguzniki/$', views.redirect_to_index, name='redirect_to_index'),


    url(r'^get_series/(?P<brand_id>[-\w]+)/', views.get_series, name='get_series'),
    url(r'^get_brands/(?P<brand_id>[-\w]+)/(?P<series_id>[-\w]+)/', views.get_brands, name='get_brand'),
    url(r'^get_sizes/(?P<brand_id>[-\w]+)/(?P<series_id>[-\w]+)/', views.get_sizes, name='get_sizes'),

    url(r'^search/$', views.search, name='search'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/(?P<series>[-\w ]+)/(?P<size>[-\w]+)/$', views.products, name='products'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/(?P<series>[-\w ]+)/$', views.products, name='products'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/$', views.products, name='products'),


]

diapers/models.py
# coding=utf-8
from django.db import models
from configobj import ConfigObj
import os.path

BASE = os.path.dirname(os.path.abspath(__file__))

basic = ConfigObj(os.path.join(BASE, 'utils/data_config/basic.ini'))
brands = ConfigObj(os.path.join(BASE, 'utils/data_config/brands.ini'))


class Brand (models.Model):
    name = models.CharField(max_length=200)
    url_name = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return u'%s' % self.name

    @staticmethod
    def set_default_data():
        for brand in brands:
            Brand.objects.update_or_create(name=str(brand))


class Series (models.Model):
    name = models.CharField(max_length=200)
    url_name = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)
    brand = models.ForeignKey(Brand)

    def __str__(self):
        return "%s - %s" % (self.brand, self.name)

    def __unicode__(self):
        return u'%s' % self.name

    @staticmethod
    def set_default_data():
        for brand in brands:
            for series in brands[brand]:
                Series.objects.update_or_create(name=series, brand=Brand.objects.get(name=str(brand)))


class Seller (models.Model):
    name = models.CharField(max_length=200)
    name_rus = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)
    url = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    @staticmethod
    def set_default_data():
        for base_gender in basic['Seller']:
            Seller.objects.update_or_create(gender=base_gender)


class Type (models.Model):
    type = models.CharField(max_length=200)
    type_rus = models.CharField(max_length=200)

    def __str__(self):
        return self.type

    @staticmethod
    def set_default_data():
        for base_type in basic['Type']:
            Type.objects.update_or_create(type=base_type)


class Gender (models.Model):
    gender = models.CharField(max_length=200)
    gender_rus = models.CharField(max_length=200)

    def __str__(self):
        return self.gender

    @staticmethod
    def set_default_data():
        for base_gender in basic['Gender']:
            Gender.objects.update_or_create(gender=base_gender)


class Product (models.Model):
    brand = models.ForeignKey(Brand)
    series = models.ForeignKey(Series, default=None, blank=True, null=True)
    type = models.ForeignKey(Type)
    gender = models.ForeignKey(Gender)
    size = models.CharField(max_length=200)
    min_weight = models.FloatField()
    max_weight = models.FloatField()
    count = models.IntegerField()

    def __unicode__(self):
        return u"%s %s %s (%s - %s кг) %s шт" % \
               (self.brand, self.series, self.size, self.min_weight, self.max_weight, self.count)


class ProductPreview (models.Model):
    description = models.TextField()
    seller = models.ForeignKey(Seller)
    brand = models.ForeignKey(Brand, default=None, blank=True, null=True)
    series = models.ForeignKey(Series, default=None, blank=True, null=True)
    url = models.TextField()
    status = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s %s - %s " % \
               (self.seller, self.brand, self.series, self.status)


class PreviewParseHistory (models.Model):
    product = models.ForeignKey(Product)
    preview = models.ForeignKey(ProductPreview)


class Stock (models.Model):
    seller = models.ForeignKey(Seller)
    product = models.ForeignKey(Product)
    url = models.TextField()
    price_unit = models.FloatField()
    price_full = models.FloatField()
    price_unit_before_discount = models.FloatField(default=-1)
    price_full_before_discount = models.FloatField(default=-1)
    in_stock = models.BooleanField(default=True)
    is_visible = models.BooleanField(default=True)  # = False if we have any errors during price parcing


class Skip (models.Model):
    seller = models.ForeignKey(Seller)
    url = models.TextField()

diapers/views/views_admin.py
# coding=utf-8

from diapers.models import Brand, Series, Product, Stock, Seller, Gender, Type, ProductPreview, PreviewParseHistory, Skip
from lxml import html
import requests
from configobj import ConfigObj
import re
import os.path
from django.http import HttpResponsePermanentRedirect
from diapers.utils import parser, suggester
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.db.models import Q


BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

shop_xpath = ConfigObj(os.path.join(BASE, 'utils/data_config/shop_xpath.ini'))
shop_urls = ConfigObj(os.path.join(BASE, 'utils/data_config/shop_urls.ini'))
brand_list = ConfigObj(os.path.join(BASE, 'utils/data_config/brands.ini'))


def admin(request):
    return render(request, 'diapers/admin.html')


#creates all brands from conf, if not existed
def update_brand_list(request):
    items_added = {}
    for brand in brand_list:
        items_added[brand] = Brand.objects.update_or_create(name=str(brand))
   # Series.set_default_data()
    return render(request, 'diapers/parse/update_brand_list.html', {'items_added': items_added})


# get all shops from db
# get all unparsed items from shops
def parse_shop_catalog(request):
    seller_name = request.GET.get('seller_name')
    items_added = {}
    if seller_name is None:
        sellers = Seller.objects.all()
        for seller in sellers:
            items_added[seller] = parser.parse_seller(seller)

    else:
        seller = Seller.objects.get(name=seller_name)
        items_added[seller] = parser.parse_seller(seller)
    return render(request, 'diapers/parse/parse_shop_catalog.html', {'items_added': items_added})


def parse_items(seller):
    seller_url = seller.url
    stock_items = Stock.objects.filter(seller=seller)

    for stock_item in stock_items:
        product_url = stock_item.url
        page = requests.get(seller_url + product_url)
        tree = html.fromstring(page.text)
        price_after_discount_xpath = shop_xpath[seller.name]['price_after_discount']
        price_after_discount = tree.xpath(price_after_discount_xpath)
        # TODO add price_before_discount
        try:
            price_after_discount = re.sub('\s+', '', price_after_discount[0])
            stock_item.price_full = price_after_discount
            stock_item.price_unit = float(price_after_discount) / stock_item.product.count
        except IndexError:
            stock_item.price_full = -1
            stock_item.price_unit = -1
        stock_item.save()


def manual_parse_result(request):
    if 'submit' in request.POST:
        new_product, created = Product.objects.get_or_create(
            size=request.POST['size'],
            min_weight=request.POST['min_weight'],
            max_weight=request.POST['max_weight'],
            count=request.POST['count'],
            gender_id=request.POST['gender'],
            brand_id=request.POST['brand'],
            series_id=request.POST.get('series', None),
            type_id=request.POST['type'])
        new_product.save()
        product_preview = ProductPreview.objects.filter(pk=request.POST['chosen_product_id']).first()
        product_preview.status = "done"
        product_preview.save()

        preview_parse_history = PreviewParseHistory(product=new_product, preview=product_preview)
        preview_parse_history.save()

        new_stock, created = Stock.objects.get_or_create(seller=product_preview.seller, product=new_product,
                                                         url=product_preview.url,
                                                         defaults={'price_unit': -1, 'price_full': -1, 'in_stock': True,
                                                                   'is_visible': True})

        new_stock.save()
    elif 'skip' in request.POST:
        product_preview = ProductPreview.objects.filter(pk=request.POST['chosen_product_id']).first()
        product_preview.status = "skip"
        product_preview.save()
        skip = Skip(seller=product_preview.seller, url=product_preview.url)
        skip.save()

    return HttpResponsePermanentRedirect(reverse('diapers:manual'))


def manual_parse(request):
    prefiltered_products = ProductPreview.objects.filter(description__icontains='')

    chosen_products = prefiltered_products.filter(~Q(status='done'), ~Q(status='skip'), ~Q(status='error')).order_by('?')
   #chosen_products = ProductPreview.objects.filter(~Q(status='done'), ~Q(status='skip')).order_by('?')
    chosen_product = chosen_products.first()
    print '111-   ' + str(suggester.suggest_brand(chosen_product))
    try:
        int(suggester.suggest_brand(chosen_product))

        print chosen_product.id
        return render(request, 'diapers/parse/manual_parse.html',
                      {'all_brands': Brand.objects.all(),
                       'all_series': Series.objects.filter(brand=suggester.suggest_brand(chosen_product)),
                       'all_types': Type.objects.all(),
                       'all_genders': Gender.objects.all(),
                       'suggest_brand': suggester.suggest_brand(chosen_product),
                       'suggest_series': suggester.suggest_series(chosen_product),
                       'suggest_size': suggester.suggest_size(chosen_product),
                       'suggest_type': suggester.suggest_type(chosen_product),
                       'suggest_gender': suggester.suggest_gender(chosen_product),
                       'suggest_min_weight': suggester.suggest_min_weight(chosen_product),
                       'suggest_max_weight': suggester.suggest_max_weight(chosen_product),
                       'suggest_count': suggester.suggest_count(chosen_product),
                       'chosen_product': chosen_product,
                       'progress_counter': chosen_products.count()})
    except ValueError:
        chosen_product.status = "error"
        chosen_product.save()
        return HttpResponsePermanentRedirect(reverse('diapers:manual'))


def update_prices_and_availability(request):
    # TODO add availability checking
    prices_parsed = parser.get_prices_and_availability()
    return render(request, 'diapers/parse/prices.html', {'prices_parsed': prices_parsed})


def recreate(request):
    # Delete products, previews and history from everywhere
   # PreviewParseHistory.objects.all().delete()
    ProductPreview.objects.all().delete()
    Product.objects.all().delete()
    # Seller recreate
    #  Seller.objects.all().delete()
    #  Seller.set_default_data()
    # Gender recreate
    Gender.objects.all().delete()
    Gender.set_default_data()
    # Brand recreate
    #  Brand.objects.all().delete()
    # Brand.set_default_data()
    # Series recreate
    Series.objects.all().delete()
    Series.set_default_data()
    # Type recreate
    Type.objects.all().delete()
    Type.set_default_data()
    # Series recreate
    #  items_added_korablik = parser.parse_shop_catalog('Korablik', False)
    #  items_added_detmir = parser.parse_shop_catalog('Detmir', False)

    return render(request, 'diapers/parse/recreate.html', {
        #      'items_added_korablik': items_added_korablik,
        #       'items_added_detmir': items_added_detmir,
        #      'items_added_ozon': items_added_ozon,
        #       'items_added': items_added_korablik + items_added_detmir  # + items_added_ozon
    })

diapers/views/views_tech.py
# coding=utf-8

import logging
from django.shortcuts import render

logger = logging.getLogger('compare')



def error404(request):
    return render(request, 'technical/404.html', status=404)


def error500(request):
    return render(request, 'technical/500.html', status=500)

diapers/templates/diapers/parse/manual_parse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'diapers/css/bootstrap.min.css' %}" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'diapers/js/bootstrap.min.js' %}"></script>
    <!-- Suggest stuff -->
    <script>
        $(document).ready(function () {
            $('select[name=series]').val({{ suggest_series }});
            $('select[name=series]').change();

            $('select[name=brand]').val({{ suggest_brand }});
            $('select[name=brand]').change();

            $('select[name=gender]').val({{ suggest_gender }});
            $('select[name=gender]').change();

            $('select[name=type]').val({{ suggest_type }});
            $('select[name=type]').change();

    })

    </script>
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <a href="{% url 'diapers:admin' %}">Админка</a>
        <br>
        <br>
        <form class="form-horizontal" action="{% url 'diapers:manual_parse_result' %}" method="post">
            {% csrf_token %}
            <fieldset>

                <!-- Form Name -->
                <legend>{{ progress_counter }} products left</legend>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="chosen_product_id">chosen_product_id</label>
                  <div class="col-md-8">
                  <a href="{{chosen_product.url }}">
                      {{chosen_product.url }}</a>

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="chosen_product_id">chosen_product_id</label>
                  <div class="col-md-8">
                  <input id="chosen_product_id" name="chosen_product_id" type="text" placeholder="" class="form-control input-md"
                         value="{{ chosen_product.id }}" readonly>

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="description">description</label>
                  <div class="col-md-8">
                  <input id="description" name="description" type="text" placeholder="" class="form-control input-md"
                         value="{{ chosen_product.description }}" readonly>

                  </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="brand">brand</label>
                  <div class="col-md-8">
                    <select id="brand" name="brand" class="form-control">
                        {% for brand in all_brands %}
                            <option value="{{ brand.id }}">{{ brand.name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="series">series</label>
                  <div class="col-md-8">
                    <select id="series" name="series" class="form-control">
                        {% for series in all_series %}
                                <option value="{{ series.id }}">{{ series.name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="type">type</label>
                  <div class="col-md-8">
                    <select id="type" name="type" class="form-control">
                        {% for type in all_types %}
                            <option value="{{ type.id }}">{{ type.type }}</option>
                        {% endfor %}
                    </select>
                  </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="gender">gender</label>
                  <div class="col-md-8">
                    <select id="gender" name="gender" class="form-control">
                        {% for gender in all_genders %}
                            <option value="{{ gender.id }}">{{ gender.gender }}</option>
                        {% endfor %}
                    </select>
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="size">size</label>
                  <div class="col-md-8">
                  <input id="size" name="size" type="text" placeholder="" class="form-control input-md"
                          value="{{ suggest_size }}">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="min_weight">min_weight</label>
                  <div class="col-md-8">
                  <input id="min_weight" name="min_weight" type="text" placeholder="" class="form-control input-md"
                          value="{{ suggest_min_weight }}">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="max_weight">max_weight</label>
                  <div class="col-md-8">
                  <input id="max_weight" name="max_weight" type="text" placeholder="" class="form-control input-md"
                          value="{{ suggest_max_weight }}">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="count">count</label>
                  <div class="col-md-8">
                  <input id="count" name="count" type="text" placeholder="" class="form-control input-md"
                         value="{{ suggest_count }}">

                  </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                  <label class="col-md-2 control-label" for="submit"></label>
                  <div class="col-md-1">
                    <button id="submit" name="submit" class="btn btn-success">submit</button>
                  </div>
                  <div class="col-md-6">
                  </div>
                   <div class="col-md-1">
                    <button id="skip" name="skip" class="btn btn-warning">skip</button>
                  </div>



                </div>

            </fieldset>
        </form>
    </div>
    <div class="col-md-2"></div>
    </div>



</body>
</html>

diapers/templates/diapers/parse/parse_shop_catalog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update product list</title>
</head>
<body>
<a href="{% url 'diapers:admin' %}">index</a>
<br>
<br>
<ul>
{% for shop, items in items_added.items %}
    <li>{{ shop }} : {{ items }}</li>
{% endfor %}
</ul>
</body>
</html>

diapers/templates/diapers/parse/prices.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Prices parsed: {{ prices_parsed }}
</body>
</html>

diapers/templates/diapers/parse/recreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
Detmir: {{ items_added_detmir }} </br>
Korablik: {{ items_added_korablik }} </br>
</br>
Total: {{ items_added }}
</body>
</html>

diapers/templates/diapers/parse/update_brand_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update brand list</title>
</head>
<body>
<a href="{% url 'diapers:admin' %}">index</a>
<br>
<br>
<ul>
{% for brand, items in items_added.items %}
    <li>{{ brand }} : {{ items }}</li>
{% endfor %}
</ul>
</body>
</html>