compare/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib import admin


admin.autodiscover()
urlpatterns = [
    url(r'^djadmin/', include(admin.site.urls)),
    url(r'^', include('diapers.urls', namespace="diapers")),
]

urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT}),)


handler404 = 'diapers.views.error404'
handler500 = 'diapers.views.error500'

diapers/urls.py
__author__ = 'asorokoumov'
from django.conf.urls import url

from . import views
from views import *

urlpatterns = [

    url(r'^admin/$', views.admin, name='admin'),

    # admin
    url(r'^parse/parse_shop_catalog/$', views.parse_shop_catalog, name='parse_shop_catalog'),
    url(r'^parse/update_brand_list/$', views.update_brand_list, name='update_brand_list'),
    url(r'^parse/recreate/$', views.recreate, name='recreate'),
    url(r'^parse/prices/$', views.update_prices_and_availability, name='update_prices_and_availability'),
    url(r'^parse/manual/$', views.manual_parse, name='manual'),
    url(r'^parse/manual_parse_result/$', views.manual_parse_result, name='manual_parse_result'),


    #  New design
    url(r'^$', views.index, name='index'),
    url(r'^podguzniki/$', views.redirect_to_index, name='redirect_to_index'),


    url(r'^get_series/(?P<brand_id>[-\w]+)/', views.get_series, name='get_series'),
    url(r'^get_brands/(?P<brand_id>[-\w]+)/(?P<series_id>[-\w]+)/', views.get_brands, name='get_brand'),
    url(r'^get_sizes/(?P<brand_id>[-\w]+)/(?P<series_id>[-\w]+)/', views.get_sizes, name='get_sizes'),

    url(r'^search/$', views.search, name='search'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/(?P<series>[-\w ]+)/(?P<size>[-\w]+)/$', views.products, name='products'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/(?P<series>[-\w ]+)/$', views.products, name='products'),
    url(r'^podguzniki/(?P<brand>[-\w ]+)/$', views.products, name='products'),


]

diapers/models.py
# coding=utf-8
from django.db import models
from configobj import ConfigObj
import os.path

BASE = os.path.dirname(os.path.abspath(__file__))

basic = ConfigObj(os.path.join(BASE, 'utils/data_config/basic.ini'))
brands = ConfigObj(os.path.join(BASE, 'utils/data_config/brands.ini'))


class Brand (models.Model):
    name = models.CharField(max_length=200)
    url_name = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return u'%s' % self.name

    @staticmethod
    def set_default_data():
        for brand in brands:
            Brand.objects.update_or_create(name=str(brand))


class Series (models.Model):
    name = models.CharField(max_length=200)
    url_name = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)
    brand = models.ForeignKey(Brand)

    def __str__(self):
        return "%s - %s" % (self.brand, self.name)

    def __unicode__(self):
        return u'%s' % self.name

    @staticmethod
    def set_default_data():
        for brand in brands:
            for series in brands[brand]:
                Series.objects.update_or_create(name=series, brand=Brand.objects.get(name=str(brand)))


class Seller (models.Model):
    name = models.CharField(max_length=200)
    name_rus = models.CharField(max_length=200)
    description = models.TextField(default=None, blank=True, null=True)
    url = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    @staticmethod
    def set_default_data():
        for base_gender in basic['Seller']:
            Seller.objects.update_or_create(gender=base_gender)


class Type (models.Model):
    type = models.CharField(max_length=200)
    type_rus = models.CharField(max_length=200)

    def __str__(self):
        return self.type

    @staticmethod
    def set_default_data():
        for base_type in basic['Type']:
            Type.objects.update_or_create(type=base_type)


class Gender (models.Model):
    gender = models.CharField(max_length=200)
    gender_rus = models.CharField(max_length=200)

    def __str__(self):
        return self.gender

    @staticmethod
    def set_default_data():
        for base_gender in basic['Gender']:
            Gender.objects.update_or_create(gender=base_gender)


class Product (models.Model):
    brand = models.ForeignKey(Brand)
    series = models.ForeignKey(Series, default=None, blank=True, null=True)
    type = models.ForeignKey(Type)
    gender = models.ForeignKey(Gender)
    size = models.CharField(max_length=200)
    min_weight = models.FloatField()
    max_weight = models.FloatField()
    count = models.IntegerField()

    def __unicode__(self):
        return u"%s %s %s (%s - %s кг) %s шт" % \
               (self.brand, self.series, self.size, self.min_weight, self.max_weight, self.count)


class ProductPreview (models.Model):
    description = models.TextField()
    seller = models.ForeignKey(Seller)
    brand = models.ForeignKey(Brand, default=None, blank=True, null=True)
    series = models.ForeignKey(Series, default=None, blank=True, null=True)
    url = models.TextField()
    status = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s %s - %s " % \
               (self.seller, self.brand, self.series, self.status)


class PreviewParseHistory (models.Model):
    product = models.ForeignKey(Product)
    preview = models.ForeignKey(ProductPreview)


class Stock (models.Model):
    seller = models.ForeignKey(Seller)
    product = models.ForeignKey(Product)
    url = models.TextField()
    price_unit = models.FloatField()
    price_full = models.FloatField()
    price_unit_before_discount = models.FloatField(default=-1)
    price_full_before_discount = models.FloatField(default=-1)
    in_stock = models.BooleanField(default=True)
    is_visible = models.BooleanField(default=True)  # = False if we have any errors during price parcing


class Skip (models.Model):
    seller = models.ForeignKey(Seller)
    url = models.TextField()

diapers/views/views_admin.py
# coding=utf-8

from diapers.models import Brand, Series, Product, Stock, Seller, Gender, Type, ProductPreview, PreviewParseHistory, Skip
from lxml import html
import requests
from configobj import ConfigObj
import re
import os.path
from django.http import HttpResponsePermanentRedirect
from diapers.utils import parser, suggester
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.db.models import Q


BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

shop_xpath = ConfigObj(os.path.join(BASE, 'utils/data_config/shop_xpath.ini'))
shop_urls = ConfigObj(os.path.join(BASE, 'utils/data_config/shop_urls.ini'))
brand_list = ConfigObj(os.path.join(BASE, 'utils/data_config/brands.ini'))


def admin(request):
    return render(request, 'diapers/admin.html')


#creates all brands from conf, if not existed
def update_brand_list(request):
    items_added = {}
    for brand in brand_list:
        items_added[brand] = Brand.objects.update_or_create(name=str(brand))
   # Series.set_default_data()
    return render(request, 'diapers/parse/update_brand_list.html', {'items_added': items_added})


# get all shops from db
# get all unparsed items from shops
def parse_shop_catalog(request):
    seller_name = request.GET.get('seller_name')
    items_added = {}
    if seller_name is None:
        sellers = Seller.objects.all()
        for seller in sellers:
            items_added[seller] = parser.parse_seller(seller)

    else:
        seller = Seller.objects.get(name=seller_name)
        items_added[seller] = parser.parse_seller(seller)
    return render(request, 'diapers/parse/parse_shop_catalog.html', {'items_added': items_added})


def parse_items(seller):
    seller_url = seller.url
    stock_items = Stock.objects.filter(seller=seller)

    for stock_item in stock_items:
        product_url = stock_item.url
        page = requests.get(seller_url + product_url)
        tree = html.fromstring(page.text)
        price_after_discount_xpath = shop_xpath[seller.name]['price_after_discount']
        price_after_discount = tree.xpath(price_after_discount_xpath)
        # TODO add price_before_discount
        try:
            price_after_discount = re.sub('\s+', '', price_after_discount[0])
            stock_item.price_full = price_after_discount
            stock_item.price_unit = float(price_after_discount) / stock_item.product.count
        except IndexError:
            stock_item.price_full = -1
            stock_item.price_unit = -1
        stock_item.save()


def manual_parse_result(request):
    if 'submit' in request.POST:
        new_product, created = Product.objects.get_or_create(
            size=request.POST['size'],
            min_weight=request.POST['min_weight'],
            max_weight=request.POST['max_weight'],
            count=request.POST['count'],
            gender_id=request.POST['gender'],
            brand_id=request.POST['brand'],
            series_id=request.POST.get('series', None),
            type_id=request.POST['type'])
        new_product.save()
        product_preview = ProductPreview.objects.filter(pk=request.POST['chosen_product_id']).first()
        product_preview.status = "done"
        product_preview.save()

        preview_parse_history = PreviewParseHistory(product=new_product, preview=product_preview)
        preview_parse_history.save()

        new_stock, created = Stock.objects.get_or_create(seller=product_preview.seller, product=new_product,
                                                         url=product_preview.url,
                                                         defaults={'price_unit': -1, 'price_full': -1, 'in_stock': True,
                                                                   'is_visible': True})

        new_stock.save()
    elif 'skip' in request.POST:
        product_preview = ProductPreview.objects.filter(pk=request.POST['chosen_product_id']).first()
        product_preview.status = "skip"
        product_preview.save()
        skip = Skip(seller=product_preview.seller, url=product_preview.url)
        skip.save()

    return HttpResponsePermanentRedirect(reverse('diapers:manual'))


def manual_parse(request):
    prefiltered_products = ProductPreview.objects.filter(description__icontains='')

    chosen_products = prefiltered_products.filter(~Q(status='done'), ~Q(status='skip'), ~Q(status='error')).order_by('?')
   #chosen_products = ProductPreview.objects.filter(~Q(status='done'), ~Q(status='skip')).order_by('?')
    chosen_product = chosen_products.first()
    print '111-   ' + str(suggester.suggest_brand(chosen_product))
    try:
        int(suggester.suggest_brand(chosen_product))

        print chosen_product.id
        return render(request, 'diapers/parse/manual_parse.html',
                      {'all_brands': Brand.objects.all(),
                       'all_series': Series.objects.filter(brand=suggester.suggest_brand(chosen_product)),
                       'all_types': Type.objects.all(),
                       'all_genders': Gender.objects.all(),
                       'suggest_brand': suggester.suggest_brand(chosen_product),
                       'suggest_series': suggester.suggest_series(chosen_product),
                       'suggest_size': suggester.suggest_size(chosen_product),
                       'suggest_type': suggester.suggest_type(chosen_product),
                       'suggest_gender': suggester.suggest_gender(chosen_product),
                       'suggest_min_weight': suggester.suggest_min_weight(chosen_product),
                       'suggest_max_weight': suggester.suggest_max_weight(chosen_product),
                       'suggest_count': suggester.suggest_count(chosen_product),
                       'chosen_product': chosen_product,
                       'progress_counter': chosen_products.count()})
    except ValueError:
        chosen_product.status = "error"
        chosen_product.save()
        return HttpResponsePermanentRedirect(reverse('diapers:manual'))


def update_prices_and_availability(request):
    # TODO add availability checking
    prices_parsed = parser.get_prices_and_availability()
    return render(request, 'diapers/parse/prices.html', {'prices_parsed': prices_parsed})


def recreate(request):
    # Delete products, previews and history from everywhere
   # PreviewParseHistory.objects.all().delete()
    ProductPreview.objects.all().delete()
    Product.objects.all().delete()
    # Seller recreate
    #  Seller.objects.all().delete()
    #  Seller.set_default_data()
    # Gender recreate
    Gender.objects.all().delete()
    Gender.set_default_data()
    # Brand recreate
    #  Brand.objects.all().delete()
    # Brand.set_default_data()
    # Series recreate
    Series.objects.all().delete()
    Series.set_default_data()
    # Type recreate
    Type.objects.all().delete()
    Type.set_default_data()
    # Series recreate
    #  items_added_korablik = parser.parse_shop_catalog('Korablik', False)
    #  items_added_detmir = parser.parse_shop_catalog('Detmir', False)

    return render(request, 'diapers/parse/recreate.html', {
        #      'items_added_korablik': items_added_korablik,
        #       'items_added_detmir': items_added_detmir,
        #      'items_added_ozon': items_added_ozon,
        #       'items_added': items_added_korablik + items_added_detmir  # + items_added_ozon
    })

diapers/views/views_tech.py
# coding=utf-8

import logging
from django.shortcuts import render

logger = logging.getLogger('compare')



def error404(request):
    return render(request, 'technical/404.html', status=404)


def error500(request):
    return render(request, 'technical/500.html', status=500)

diapers/templates/diapers/admin.html
<!DOCTYPE html>
<html lang="en">
   <head>
      {% load staticfiles %}
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="http://templatecycle.com/demo/bootclassified-v1.4/dist/assets/ico/favicon.png">
      <title>Бренды</title>
      <link rel="stylesheet" type="text/css" href="{% static 'diapers/css/bootstrap.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'diapers/css/style.css' %}" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class=" pace-done">
      <div class="pace  pace-inactive">
         <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
            <div class="pace-progress-inner"></div>
         </div>
         <div class="pace-activity"></div>
      </div>
      <div id="wrapper">
         <div class="header">
            <nav class="navbar   navbar-site navbar-default" role="navigation">
               <div class="container">
                  <div class="navbar-header">
                     <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                     <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                     </button>
                     <span class="logo-icon"><i class="icon icon-search-1 ln-shadow-logo shape-0"></i> </span> Krot.<span>io </span> </a>
                  </div>
                  <div class="navbar-collapse collapse">
                     <ul class="nav navbar-nav navbar-left">
                     </ul>
                     <ul class="nav navbar-nav navbar-right">
                        <li><a href="">Как это работает</a></li>
                        <li><a href="">О нас</a></li>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
         <div class="main-container">
            <div class="container">
               <div class="col-lg-12 content-box ">
                  <div class="row row-featured row-featured-category row-featured-company">
                     <div class="col-lg-12  box-title no-border" style="background: #ffffff ;">
                        <div class="inner">
                           <h2><span>Админка</span> <a class="sell-your-item" href=""> <i class="  icon-th-list"></i> </a></h2>
                        </div>
                     </div>
                     <div class="col-lg-9 f-category" style="height: 100px;">
                        <a href="{% url 'diapers:update_brand_list' %}">
                           <h5><span class="company-name">Обновить список брендов</span></h5>
                        </a>
                     </div>
                     <div class="col-lg-4  f-category" style="height: 100px;">
                        <a href="{% url 'diapers:parse_shop_catalog' %}?seller_name=Korablik">
                           <h5><span class="company-name">Получить новые продукты из магазина Кораблик</span></h5>
                        </a>
                     </div>
                     <div class="col-lg-4  f-category" style="height: 100px;">
                        <a href="{% url 'diapers:parse_shop_catalog' %}?seller_name=Ozon">
                           <h5><span class="company-name">Получить новые продукты из магазина Ozon</span></h5>
                        </a>
                     </div>
                     <div class="col-lg-4  f-category" style="height: 100px;">
                        <a href="{% url 'diapers:parse_shop_catalog' %}?seller_name=Akusherstvo">
                           <h5><span class="company-name">Получить новые продукты из магазина Акушерство</span></h5>
                        </a>
                     </div>

                     <div class="col-lg-4  f-category" style="height: 100px;">
                        <a href="{% url 'diapers:parse_shop_catalog' %}?seller_name=Detmir">
                           <h5><span class="company-name">Получить новые продукты из магазина Детский Мир</span></h5>
                        </a>
                     </div>

                     <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4 f-category" style="height: 100px;">
                        <a href="{% url 'diapers:update_prices_and_availability' %}">
                           <h5><span class="company-name">Обновить цены</span></h5>
                        </a>
                     </div>


                     <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4 f-category" style="height: 100px;">
                        <a href="{% url 'diapers:manual' %}">
                           <h5><span class="company-name">Ручная обработка</span></h5>
                        </a>
                     </div>



                  </div>
               </div>
               <div style="clear: both"></div>
               <div style="clear: both"></div>
               <div class="col-lg-12 content-box ">
                  <div class="row row-featured">
                     <div style="clear: both"></div>
                     <div class=" relative  content  clearfix">
                        <div class="">
                           <div class="tab-lite">
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="footer" id="footer">
            <div class="container">
               <ul class=" pull-right navbar-link footer-nav">
                  <li> © 2016 krot.io</li>
               </ul>
            </div>
         </div>
      </div>

      <script src="{% static 'diapers/js/jquery.min.js' %}"  type="text/javascript"></script>
      <script src="{% static 'diapers/js/bootstrap.min.js' %}"  type="text/javascript"></script>
   </body>
</html>

diapers/templates/diapers/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="verify-admitad" content="171ac4e210" />
    <meta name="yandex-verification" content="80ad190171b3724f" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}

    <link rel="icon" href="../../favicon.ico">

    <title>Поиск дешевых подгузников</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'diapers/css/cover.css' %}" />
    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '2134742056759326');
      fbq('track', 'PageView');
    </script>

    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=2134742056759326&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      <!-- start Mixpanel --><script type="text/javascript">(function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
        0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
        for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
        MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);
        mixpanel.init("016c1f37923ff4820de9cf0da1fd4cdb");</script><!-- end Mixpanel -->
   <script type="text/javascript">
       mixpanel.track("Index page opened");
    </script>
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

         <div class="masthead clearfix ">
             <nav class="navbar navbar-default">
             <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- <a class="navbar-brand" href="#">
              Brand
              </a>-->
            </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
      <!--       <li><a href="#">Свяжитесь с нами</a></li> -->

          </ul>
        </div><!-- /.navbar-collapse -->
                 </nav>
          </div>





          <div class="inner cover">
            <h1 class="cover-heading">Поиск дешевых подгузников</h1>
            <p class="lead">
              <form class="form-horizontal" id="search_form" action="{% url 'diapers:search' %}" method="post" target="_blank">
                 {% csrf_token %}
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-12 col-md-4" style="padding-right:5px; padding-left:5px; padding-bottom:5px">
                        <select id="brand" name="brand" class="form-control">
                          <option value="-1">Бренд</option>
                            {% for brand_item in brands %}
                              <option value="{{brand_item.id}}">{{brand_item.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-md-4" style="padding-right:5px; padding-left:5px; padding-bottom:5px">
                        <select id="series" name="series" class="form-control">
                            <option value="-1">Серия</option>
                            {% for series_item in series %}
                              <option value="{{series_item.id}}">{{series_item.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-md-4" style="padding-right:5px; padding-left:5px; padding-bottom:5px">
                        <select id="size" name="size" class="form-control">
                          <option value="-1">Размер</option>
                            {% for size_item in sizes %}
                              <option value="{{size_item}}">{{size_item}}</option>
                            {% endfor %}
                        </select>
                    </div>

                  </div>


                </div>
                <button type="submit" onclick="yaCounter39130756.reachGoal('search_on_main'); return true; mixpanel.track('Search');" class="btn btn-lg btn-default">Найти</button>
              </form>
            </p>
          </div>
          <div class="mastfoot">
            <div class="inner">
             <!-- <p></p> -->
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter49236736 = new Ya.Metrika2({ id:49236736, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/49236736" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    <script src="{% static 'diapers/js/jquery.min.js' %}"  type="text/javascript"></script>
    <script src="{% static 'diapers/js/script.js' %}"  type="text/javascript"></script>
  </body>
</html>